
INSERT INTO countries (id, country, country_code, stc, xr, created) VALUES
(1, 'United States - US', 'US', 1, 1, NULL),
(2, 'Afghanistan - AF', 'AF', 1, 0, NULL),
(3, 'Albania - AL', 'AL', 1, 0, NULL),
(4, 'Algeria - DZ', 'DZ', 1, 0, NULL),
(5, 'American Samoa - AS', 'AS', 1, 0, NULL),
(6, 'Andorra - AD', 'AD', 1, 0, NULL),
(7, 'Angola - AO', 'AO', 1, 0, NULL),
(8, 'Anguilla - AI', 'AI', 1, 0, NULL),
(9, 'Antarctica - AQ', 'AQ', 1, 0, NULL),
(10, 'Antigua and Barbuda - AG', 'AG', 1, 0, NULL),
(11, 'Argentina - AR', 'AR', 1, 0, NULL),
(12, 'Armenia - AM', 'AM', 1, 0, NULL),
(13, 'Aruba - AW', 'AW', 1, 0, NULL),
(14, 'Australia - AU', 'AU', 1, 0, NULL),
(15, 'Austria - AT', 'AT', 1, 0, NULL),
(16, 'Azerbaijan - AZ', 'AZ', 1, 0, NULL),
(17, 'Bahamas - BS', 'BS', 1, 0, NULL),
(18, 'Bahrain - BH', 'BH', 1, 0, NULL),
(19, 'Bangladesh - BD', 'BD', 1, 0, NULL),
(20, 'Barbados - BB', 'BB', 1, 0, NULL),
(21, 'Belarus - BY', 'BY', 1, 0, NULL),
(22, 'Belgium - BE', 'BE', 1, 0, NULL),
(23, 'Belize - BZ', 'BZ', 1, 0, NULL),
(24, 'Benin - BJ', 'BJ', 1, 0, NULL),
(25, 'Bermuda - BM', 'BM', 1, 0, NULL),
(26, 'Bhutan - BT', 'BT', 1, 0, NULL),
(27, 'Bolivia - BO', 'BO', 1, 0, NULL),
(28, 'Bosnia and Herzegovina - BA', 'BA', 1, 0, NULL),
(29, 'Botswana - BW', 'BW', 1, 0, NULL),
(30, 'Bouvet Island - BV', 'BV', 1, 0, NULL),
(31, 'Brazil - BR', 'BR', 1, 0, NULL),
(32, 'British Indian Ocean Terr - IO', 'IO', 1, 0, NULL),
(33, 'Brunei Darussalam - BN', 'BN', 1, 0, NULL),
(34, 'Bulgaria - BG', 'BG', 1, 0, NULL),
(35, 'Burkina Faso - BF', 'BF', 1, 0, NULL),
(36, 'Burundi - BI', 'BI', 1, 0, NULL),
(37, 'Cambodia - KH', 'KH', 1, 0, NULL),
(38, 'Cameroon - CM', 'CM', 1, 0, NULL),
(39, 'Canada - CA', 'CA', 1, 1, NULL),
(40, 'Cape Verde - CV', 'CV', 1, 0, NULL),
(41, 'Cayman Islands - KY', 'KY', 1, 0, NULL),
(42, 'Central African Republic - CF', 'CF', 1, 0, NULL),
(43, 'Chad - TD', 'TD', 1, 0, NULL),
(44, 'Chile - CL', 'CL', 1, 0, NULL),
(45, 'China - CN', 'CN', 1, 0, NULL),
(46, 'Christmas Island - CX', 'CX', 1, 0, NULL),
(47, 'Cocos (Keeling) Islands - CC', 'CC', 1, 0, NULL),
(48, 'Colombia - CO', 'CO', 1, 0, NULL),
(49, 'Comoros - KM', 'KM', 1, 0, NULL),
(50, 'Congo - CG', 'CG', 1, 0, NULL),
(51, 'Cook Islands - CK', 'CK', 1, 0, NULL),
(52, 'Costa Rica - CR', 'CR', 1, 0, NULL),
(53, 'Cote D''Ivoire (Ivory Coas - CI', 'CI', 1, 0, NULL),
(54, 'Croatia (Hrvatska) - HR', 'HR', 1, 0, NULL),
(55, 'Cuba - CU', 'CU', 1, 0, NULL),
(56, 'Cyprus - CY', 'CY', 1, 0, NULL),
(57, 'Czech Republic - CZ', 'CZ', 1, 0, NULL),
(58, 'Czechoslovakia (former) - CS', 'CS', 1, 0, NULL),
(59, 'Denmark - DK', 'DK', 1, 0, NULL),
(60, 'Djibouti - DJ', 'DJ', 1, 0, NULL),
(61, 'Dominica - DM', 'DM', 1, 0, NULL),
(62, 'Dominican Republic - DO', 'DO', 1, 0, NULL),
(63, 'East Timor - TP', 'TP', 1, 0, NULL),
(64, 'Ecuador - EC', 'EC', 1, 0, NULL),
(65, 'Egypt - EG', 'EG', 1, 0, NULL),
(66, 'El Salvador - SV', 'SV', 1, 0, NULL),
(67, 'Equatorial Guinea - GQ', 'GQ', 1, 0, NULL),
(68, 'Eritrea - ER', 'ER', 1, 0, NULL),
(69, 'Estonia - EE', 'EE', 1, 0, NULL),
(70, 'Ethiopia - ET', 'ET', 1, 0, NULL),
(71, 'Falkland Islands (Malvina - FK', 'FK', 1, 0, NULL),
(72, 'Faroe Islands - FO', 'FO', 1, 0, NULL),
(73, 'Fiji - FJ', 'FJ', 1, 0, NULL),
(74, 'Finland - FI', 'FI', 1, 0, NULL),
(75, 'France - FR', 'FR', 1, 0, NULL),
(76, 'France, Metropolitan - FX', 'FX', 1, 0, NULL),
(77, 'French Guiana - GF', 'GF', 1, 0, NULL),
(78, 'French Polynesia - PF', 'PF', 1, 0, NULL),
(79, 'French Southern Territori - TF', 'TF', 1, 0, NULL),
(80, 'Gabon - GA', 'GA', 1, 0, NULL),
(81, 'Gambia - GM', 'GM', 1, 0, NULL),
(82, 'Georgia - GE', 'GE', 1, 0, NULL),
(83, 'Germany - DE', 'DE', 1, 0, NULL),
(84, 'Ghana - GH', 'GH', 1, 0, NULL),
(85, 'Gibraltar - GI', 'GI', 1, 0, NULL),
(86, 'Great Britain (UK) - GB', 'GB', 1, 0, NULL),
(87, 'Greece - GR', 'GR', 1, 0, NULL),
(88, 'Greenland - GL', 'GL', 1, 0, NULL),
(89, 'Grenada - GD', 'GD', 1, 0, NULL),
(90, 'Guadeloupe - GP', 'GP', 1, 0, NULL),
(91, 'Guam - GU', 'GU', 1, 0, NULL),
(92, 'Guatemala - GT', 'GT', 1, 0, NULL),
(93, 'Guinea - GN', 'GN', 1, 0, NULL),
(94, 'Guinea-Bissau - GW', 'GW', 1, 0, NULL),
(95, 'Guyana - GY', 'GY', 1, 0, NULL),
(96, 'Haiti - HT', 'HT', 1, 0, NULL),
(97, 'Heard and McDonald Island - HM', 'HM', 1, 0, NULL),
(98, 'Honduras - HN', 'HN', 1, 0, NULL),
(99, 'Hong Kong - HK', 'HK', 1, 0, NULL),
(100, 'Hungary - HU', 'HU', 1, 0, NULL),
(101, 'Iceland - IS', 'IS', 1, 0, NULL),
(102, 'India - IN', 'IN', 1, 0, NULL),
(103, 'Indonesia - ID', 'ID', 1, 0, NULL),
(104, 'Iran - IR', 'IR', 1, 0, NULL),
(105, 'Iraq - IQ', 'IQ', 1, 0, NULL),
(106, 'Ireland - IE', 'IE', 1, 0, NULL),
(107, 'Israel - IL', 'IL', 1, 0, NULL),
(108, 'Italy - IT', 'IT', 1, 0, NULL),
(109, 'Jamaica - JM', 'JM', 1, 0, NULL),
(110, 'Japan - JP', 'JP', 1, 0, NULL),
(111, 'Jordan - JO', 'JO', 1, 0, NULL),
(112, 'Kazakhstan - KZ', 'KZ', 1, 0, NULL),
(113, 'Kenya - KE', 'KE', 1, 0, NULL),
(114, 'Kiribati - KI', 'KI', 1, 0, NULL),
(115, 'Korea (North) - KP', 'KP', 1, 0, NULL),
(116, 'Korea (South) - KR', 'KR', 1, 0, NULL),
(117, 'Kuwait - KW', 'KW', 1, 0, NULL),
(118, 'Kyrgyzstan - KG', 'KG', 1, 0, NULL),
(119, 'Laos - LA', 'LA', 1, 0, NULL),
(120, 'Latvia - LV', 'LV', 1, 0, NULL),
(121, 'Lebanon - LB', 'LB', 1, 0, NULL),
(122, 'Lesotho - LS', 'LS', 1, 0, NULL),
(123, 'Liberia - LR', 'LR', 1, 0, NULL),
(124, 'Libya - LY', 'LY', 1, 0, NULL),
(125, 'Liechtenstein - LI', 'LI', 1, 0, NULL),
(126, 'Lithuania - LT', 'LT', 1, 0, NULL),
(127, 'Luxembourg - LU', 'LU', 1, 0, NULL),
(128, 'Macau - MO', 'MO', 1, 0, NULL),
(129, 'Macedonia - MK', 'MK', 1, 0, NULL),
(130, 'Madagascar - MG', 'MG', 1, 0, NULL),
(131, 'Malawi - MW', 'MW', 1, 0, NULL),
(132, 'Malaysia - MY', 'MY', 1, 0, NULL),
(133, 'Maldives - MV', 'MV', 1, 0, NULL),
(134, 'Mali - ML', 'ML', 1, 0, NULL),
(135, 'Malta - MT', 'MT', 1, 0, NULL),
(136, 'Marshall Islands - MH', 'MH', 1, 0, NULL),
(137, 'Martinique - MQ', 'MQ', 1, 0, NULL),
(138, 'Mauritania - MR', 'MR', 1, 0, NULL),
(139, 'Mauritius - MU', 'MU', 1, 0, NULL),
(140, 'Mayotte - YT', 'YT', 1, 0, NULL),
(141, 'Mexico - MX', 'MX', 1, 0, NULL),
(142, 'Micronesia - FM', 'FM', 1, 0, NULL),
(143, 'Moldova - MD', 'MD', 1, 0, NULL),
(144, 'Monaco - MC', 'MC', 1, 0, NULL),
(145, 'Mongolia - MN', 'MN', 1, 0, NULL),
(146, 'Montserrat - MS', 'MS', 1, 0, NULL),
(147, 'Morocco - MA', 'MA', 1, 0, NULL),
(148, 'Mozambique - MZ', 'MZ', 1, 0, NULL),
(149, 'Myanmar - MM', 'MM', 1, 0, NULL),
(150, 'Namibia - NA', 'NA', 1, 0, NULL),
(151, 'Nauru - NR', 'NR', 1, 0, NULL),
(152, 'Nepal - NP', 'NP', 1, 0, NULL),
(153, 'Netherlands - NL', 'NL', 1, 0, NULL),
(154, 'Netherlands Antilles - AN', 'AN', 1, 0, NULL),
(155, 'Neutral Zone - NT', 'NT', 1, 0, NULL),
(156, 'New Caledonia - NC', 'NC', 1, 0, NULL),
(157, 'New Zealand (Aotearoa) - NZ', 'NZ', 1, 0, NULL),
(158, 'Nicaragua - NI', 'NI', 1, 0, NULL),
(159, 'Niger - NE', 'NE', 1, 0, NULL),
(160, 'Nigeria - NG', 'NG', 1, 0, NULL),
(161, 'Niue - NU', 'NU', 1, 0, NULL),
(162, 'Norfolk Island - NF', 'NF', 1, 0, NULL),
(163, 'Norway - NO', 'NO', 1, 0, NULL),
(164, 'Oman - OM', 'OM', 1, 0, NULL),
(165, 'Pakistan - PK', 'PK', 1, 0, NULL),
(166, 'Palau - PW', 'PW', 1, 0, NULL),
(167, 'Panama - PA', 'PA', 1, 0, NULL),
(168, 'Papua New Guinea - PG', 'PG', 1, 0, NULL),
(169, 'Paraguay - PY', 'PY', 1, 0, NULL),
(170, 'Peru - PE', 'PE', 1, 0, NULL),
(171, 'Philippines - PH', 'PH', 1, 0, NULL),
(172, 'Pitcairn - PN', 'PN', 1, 0, NULL),
(173, 'Poland - PL', 'PL', 1, 0, NULL),
(174, 'Portugal - PT', 'PT', 1, 0, NULL),
(175, 'Puerto Rico - PR', 'PR', 1, 0, NULL),
(176, 'Qatar - QA', 'QA', 1, 0, NULL),
(177, 'Reunion - RE', 'RE', 1, 0, NULL),
(178, 'Romania - RO', 'RO', 1, 0, NULL),
(179, 'Russian Federation - RU', 'RU', 1, 0, NULL),
(180, 'Rwanda - RW', 'RW', 1, 0, NULL),
(181, 'S. Georgia and S. Sandwic - GS', 'GS', 1, 0, NULL),
(182, 'Saint Kitts and Nevis - KN', 'KN', 1, 0, NULL),
(183, 'Saint Lucia - LC', 'LC', 1, 0, NULL),
(184, 'Saint Vincent and the Gre - VC', 'VC', 1, 0, NULL),
(185, 'Samoa - WS', 'WS', 1, 0, NULL),
(186, 'San Marino - SM', 'SM', 1, 0, NULL),
(187, 'Sao Tome and Principe - ST', 'ST', 1, 0, NULL),
(188, 'Saudi Arabia - SA', 'SA', 1, 0, NULL),
(189, 'Senegal - SN', 'SN', 1, 0, NULL),
(190, 'Serbia and Montenegro - CS', 'CS', 1, 0, NULL),
(191, 'Seychelles - SC', 'SC', 1, 0, NULL),
(192, 'Sierra Leone - SL', 'SL', 1, 0, NULL),
(193, 'Singapore - SG', 'SG', 1, 0, NULL),
(194, 'Slovak Republic - SK', 'SK', 1, 0, NULL),
(195, 'Slovenia - SI', 'SI', 1, 0, NULL),
(196, 'Solomon Islands - Sb', 'Sb', 1, 0, NULL),
(197, 'Somalia - SO', 'SO', 1, 0, NULL),
(198, 'South Africa - ZA', 'ZA', 1, 0, NULL),
(199, 'Spain - ES', 'ES', 1, 0, NULL),
(200, 'Sri Lanka - LK', 'LK', 1, 0, NULL),
(201, 'St. Helena - SH', 'SH', 1, 0, NULL),
(202, 'St. Pierre and Miquelon - PM', 'PM', 1, 0, NULL),
(203, 'Sudan - SD', 'SD', 1, 0, NULL),
(204, 'Suriname - SR', 'SR', 1, 0, NULL),
(205, 'Svalbard and Jan Mayen Is - SJ', 'SJ', 1, 0, NULL),
(206, 'Swaziland - SZ', 'SZ', 1, 0, NULL),
(207, 'Sweden - SE', 'SE', 1, 0, NULL),
(208, 'Switzerland - CH', 'CH', 1, 0, NULL),
(209, 'Syria - SY', 'SY', 1, 0, NULL),
(210, 'Taiwan - TW', 'TW', 1, 0, NULL),
(211, 'Tajikistan - TJ', 'TJ', 1, 0, NULL),
(212, 'Tanzania - TZ', 'TZ', 1, 0, NULL),
(213, 'Thailand - TH', 'TH', 1, 0, NULL),
(214, 'Togo - TG', 'TG', 1, 0, NULL),
(215, 'Tokelau - TK', 'TK', 1, 0, NULL),
(216, 'Tonga - TO', 'TO', 1, 0, NULL),
(217, 'Trinidad and Tobago - TT', 'TT', 1, 0, NULL),
(218, 'Tunisia - TN', 'TN', 1, 0, NULL),
(219, 'Turkey - TR', 'TR', 1, 0, NULL),
(220, 'Turkmenistan - TM', 'TM', 1, 0, NULL),
(221, 'Turks and Caicos Islands - TC', 'TC', 1, 0, NULL),
(222, 'Tuvalu - TV', 'TV', 1, 0, NULL),
(223, 'Uganda - UG', 'UG', 1, 0, NULL),
(224, 'Ukraine - UA', 'UA', 1, 0, NULL),
(225, 'United Arab Emirates - AE', 'AE', 1, 0, NULL),
(226, 'United Kingdom - UK', 'UK', 1, 0, NULL),
(227, 'United States - US', 'US', 1, 0, NULL),
(228, 'Uruguay - UY', 'UY', 1, 0, NULL),
(229, 'US Minor Outlying Islands - UM', 'UM', 1, 0, NULL),
(230, 'Uzbekistan - UZ', 'UZ', 1, 0, NULL),
(231, 'Vanuatu - VU', 'VU', 1, 0, NULL),
(232, 'Vatican City State (Holy - VA', 'VA', 1, 0, NULL),
(233, 'Venezuela - VE', 'VE', 1, 0, NULL),
(234, 'Viet Nam - VN', 'VN', 1, 0, NULL),
(235, 'Virgin Islands (British) - VG', 'VG', 1, 0, NULL),
(236, 'Virgin Islands (U.S.) - VI', 'VI', 1, 0, NULL),
(237, 'Wallis and Futuna Islands - WF', 'WF', 1, 0, NULL),
(238, 'Western Sahara - EH', 'EH', 1, 0, NULL),
(239, 'Yemen - YE', 'YE', 1, 0, NULL),
(240, 'Yugoslavia - YU', 'YU', 1, 0, NULL),
(241, 'Zaire - ZR', 'ZR', 1, 0, NULL),
(242, 'Zambia - ZM', 'ZM', 1, 0, NULL),
(243, 'Zimbabwe - ZW', 'ZW', 1, 0, NULL);
	
	
	

INSERT INTO posts (id, page, title, body) VALUES
(3, 'front', 'News &amp; Updates', 'Sed orci risus, varius interdum suscipit in, lacinia id enim. Proin ultricies leo ut lacus eleifend sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec a tortor metus, non dictum orci. Sed at posuere mauris. Vivamus augue enim, facilisis et tempus vitae, pulvinar iaculis.');
	
	
INSERT INTO settings (1, category, key, value) VALUES
(1, 'site', 'keywords', ''),
(2, 'site', 'description', ''),
(3, 'site', 'copyright', 'Copyright 2010 South Florida Creations'),
(4, 'paypal', 'address', ''),
(5, 'site', 'title', 'pCart by South Florida Creations'),
(6, 'site', 'company', 'pCart'),
(7, 'site', 'vibrators', ''),
(8, 'front', 'best_sellers', 'Sed orci risus, varius interdum suscipit in, lacinia id enim. Proin ultricies leo ut lacus eleifend sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec a tortor metus, non dictum orci. Sed at posuere mauris. Vivamus augue enim, facilisis et tempus vitae, pulvinar iaculis.'),
(9, 'front', 'most_popular', 'Sed orci risus, varius interdum suscipit in, lacinia id enim. Proin ultricies leo ut lacus eleifend sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec a tortor metus, non dictum orci. Sed at posuere mauris. Vivamus augue enim, facilisis et tempus vitae, pulvinar iaculis.'),
(10, 'email', 'smtp_host', ''),
(11, 'email', 'stmp_user', ''),
(12, 'email', 'smtp_pass', ''),
(13, 'email', 'from', ''),
(14, 'site', 'address', ''),
(15, 'site', 'google_analytics', ''),
(16, 'email', 'smtp_port', '25'),
(17, 'email', 'smtp_type', 'open');
	
	

INSERT INTO users (id, fname, lname, username, email, password, active, created, modified) VALUES
(54, 'System', 'Admin', 'admin', '', 'c828a75ed418639db881de3e81a47f6a5512de7e', 1, NULL, NULL);